# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 362)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setBold(True)
        Form.setFont(font)
        Form.setStyleSheet("QWidget{\n"
"    background-color:rgb(58, 179, 255)\n"
"}\n"
"QLabel{\n"
"color:\'green\'\n"
"}")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(100, 70, 161, 41))
        self.pushButton.setStyleSheet("QWidget{\n"
"    background-color:red\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(110, 170, 181, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel{\n"
"    font:\'Times New Roman\'\n"
"}")
        self.label.setObjectName("label")
        self.pushButton.clicked.connect(self.clicked_btn)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def clicked_btn(self):
        self.label.setText('This is new text!!!')

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Click me!"))
        self.label.setText(_translate("Form", "This is text"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
